### ISSUE TITLE
Combining tests

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#12]
Is there a way to indicate in a package A to run the tests for package B and take the influence onto the coverage of package A into account?

In this [example](https://github.com/homalg-project/Algebroids/blob/master/.circleci/config.yml#L25) `Algebroids` invokes the tests of `FunctorCategories`.

**Comment by zickgraf** [comment]
Yes, that should be exactly the functionality of `ci_additional_packages_to_test`, see `GradedCategories`.

**Comment by mohamed-barakat** [comment]
Wonderful, thank you very much.
