### ISSUE TITLE
PDF documentation

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#14]
Even if there is a release, it would still make sense to make the badge doc|stable point to the PDF of the documentation, where all the LaTeX commands are properly compiled. It would be nice to have an option for switching between the PDF and the HTML documentation, or even both.

**Comment by zickgraf** [comment]
Building the PDF of the latest *stable* version is difficult, as it would have to be connected to the release process somehow. Adding an additional link to the PDF of the latest *dev* (=master) version would be easy.

I see two possibilities for an interface:
1. Remove automatic detection of the HTML docu and introduce two switches `doc_html` and `doc_pdf`.
2. Keep the automatic detection of the HTML docu and only add `doc_pdf`.

**Comment by mohamed-barakat** [comment]
> Building the PDF of the latest _stable_ version is difficult, as it would have to be connected to the release process somehow. 

I only mean in conjunction with a release process.

**Comment by mohamed-barakat** [comment]
> I see two possibilities for an interface:
> 
> 1. Remove automatic detection of the HTML docu and introduce two switches `doc_html` and `doc_pdf`.
> 2. Keep the automatic detection of the HTML docu and only add `doc_pdf`.

I prefer 2.

**Comment by mohamed-barakat** [comment]
Another option to consider is to link again the mathjax version of the HTML manual; compare

* [mathjax on](https://homalg-project.github.io/InternalModules/doc/chap1_mj.html#X85FE51788368C0F3)
* [mathjax off](https://homalg-project.github.io/InternalModules/doc/chap1.html#X85FE51788368C0F3)

**Comment by mohamed-barakat** [comment]
> Building the PDF of the latest _stable_ version is difficult, as it would have to be connected to the release process somehow. Adding an additional link to the PDF of the latest _dev_ (=master) version would be easy.

I think I now understand your statement: I thought that the gh-pages includes the PDF manual beside the HTML manual. I was wrong.

**Comment by zickgraf** [comment]
I assume it would not be too hard to upload the PDF during the release process, but this it out of the scope of PackageJanitor as long as it does not include the release process.

Would linking to the MathJax-Version be a solution for now?

**Comment by mohamed-barakat** [comment]
> I assume it would not be too hard to upload the PDF during the release process, but this it out of the scope of PackageJanitor as long as it does not include the release process.
> 
> Would linking to the MathJax-Version be a solution for now?

Yes, this would be a solution for now. Thank you very much.
