### ISSUE TITLE
Is there a way to disable the search for tabs in example files?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#25]
LazyCategories uses tabs in its output, here is an example: [SnakeInAlgebroid](https://github.com/homalg-project/LazyCategories/blob/master/examples/SnakeInAlgebroid.g#L64).

Is there a way to disable the search for tabs in example files?

**Comment by zickgraf** [comment]
> Is there a way to disable the search for tabs in example files?

Currently not. My first question would be: Do you really need tabs, our would 4 or 8 spaces do the trick? (and at the same time be more portable by not depending on a certain tab width).

**Comment by mohamed-barakat** [comment]
Currently, I needed it for
```
Print( count, ".\t", ...)
```
where `count` is a number.

However, I can of course replace this by asking about the number of digits in `count`.

So you are right and it is avoidable. Please keep this issue open until I close with a commit in `LazyCategories`.
