### ISSUE TITLE
LICENSE -> LICENSE.md

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#27]
It would be nice to detect the license in `PackageInfo.g`, delete `/LICENSE` and replace it with `/LICENSE.md` from

https://github.com/IQAndreas/markdown-licenses

**Comment by mohamed-barakat** [comment]
See: https://github.com/homalg-project/HomalgProject.jl/blob/master/LICENSE.md

**Comment by zickgraf** [comment]
Two things:

1. I'm not aware of any of our GAP packages having a license differing from "GPL-2.0-or-later". Do we really need an automatic detection at this point?
2. I'm hesitant to include license files from a third party.

My suggestion: GitHub has the ability to auto detect the license, see for example [this repository](https://github.com/neos/neos-development-collection) in the sidebar. If it recognizes the license, it displays a nice header with a summary of the essential points: https://github.com/neos/neos-development-collection/blob/master/LICENSE It should not be hard to make this work for our repositories, and the header might be more useful to readers than having a markdown formatted version. What do you think?

**Comment by zickgraf** [comment]
As an example, I have added the [official version](https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt) of the GPLv2 to my `FinSetsForCAP`, see:

https://github.com/zickgraf/FinSetsForCAP
https://github.com/zickgraf/FinSetsForCAP/blob/master/LICENSE

**Comment by mohamed-barakat** [comment]
> 1. I'm not aware of any of our GAP packages having a license differing from "GPL-2.0-or-later". Do we really need an automatic detection at this point?

You are right. GPL-2.0-or-later would suffice for the moment.

> 2. I'm hesitant to include license files from a third party.

I have downloaded and compared [gnu-gpl-v2.0.md](https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-gpl-v2.0.md) and apart from the markdown formatting, they are identical. I am also not aware that one is obliged to use 

> My suggestion: GitHub has the ability to auto detect the license, see for example [this repository](https://github.com/neos/neos-development-collection) in the sidebar. If it recognizes the license, it displays a nice header with a summary of the essential points: https://github.com/neos/neos-development-collection/blob/master/LICENSE It should not be hard to make this work for our repositories, and the header might be more useful to readers than having a markdown formatted version. What do you think?

Very good point. I agree :)
