### ISSUE TITLE
Is it possible to add the section Dependencies to the footer?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#38]
This would make the subsection "About" above this technical table, e.g., here:

https://github.com/homalg-project/IntrinsicModules

**Comment by zickgraf** [comment]
It certainly is possible, feel free to provide a PR if you like.

I think we should also discuss this in a bigger context:
1. I would like to move more content from the gh-pages branch (i.e., https://homalg-project.github.io/FinSetsForCAP/ for example) to the README file.
2. We should think about our "typical user" or "target user" for the READMEs: A programmer new to GAP? A GAP programmer new to CAP? A referee (programmer or non-programmer) who wants to evaluate our packages? etc.

**Comment by mohamed-barakat** [comment]
> It certainly is possible, feel free to provide a PR if you like.

Thanks, I will.

> I think we should also discuss this in a bigger context:
> 
> 1. I would like to move more content from the gh-pages branch (i.e., https://homalg-project.github.io/FinSetsForCAP/ for example) to the README file.

One difference between`README.md` and the `gh-pages` branch is that the latter includes version-specific information extracted from `PackageInfo.g` *after* the commit is finalized.

> 2. We should think about our "typical user" or "target user" for the READMEs: A programmer new to GAP? A GAP programmer new to CAP? A referee (programmer or non-programmer) who wants to evaluate our packages? etc.

* `CAP`-based packages should be marked as such in `PackageJantior`.
* One could then add a link to a subpage of our new homepage, preferably to a page that includes such information at a central place.

**Comment by zickgraf** [comment]
> One difference between`README.md` and the `gh-pages` branch is that the latter includes version-specific information extracted from `PackageInfo.g`

Yes, and I have some ideas how we could make this information dynamically available in the README, for example via custom shields.io endpoints: https://shields.io/endpoint We do not have to discuss this now, that are just ideas floating in my head :D
