### ISSUE TITLE
Link to deposited

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#45]
It would be nice if for the status deposited, e.g. [here](https://homalg-project.github.io/docs/homalg_project/), the word deposited links to the GAP package subpage, e.g. [here](https://www.gap-system.org/Packages/homalg.html).

Another future enhancement would be to see the current version and the deposited version.

**Comment by zickgraf** [comment]
> Another future enhancement would be to see the current version and the deposited version.

Links to the current version would be possible once a majority of the packages uses the most recent `PackageJanitor`. Links to the deposited version would need some interface for querying the version information.
