### ISSUE TITLE
How to replace old behavior of `maketest.commands`?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#47]
How can I instruct `PackageJanitor` to add these [two lines](https://github.com/homalg-project/PrimaryDecomposition/blob/2d6809f1d9200d7da384154bb29fb9faf26e5964/tst/testall.g#L15-L16)

```
HOMALG.SuppressParityInViewObjForCommutativeStructureObjects := true;
PRIMARY_DECOMPOSITION.RandomSource := RandomSource( IsMersenneTwister );
```

to `000_LoadPackage.tst`?

**Comment by zickgraf** [comment]
Currently, there is no way to to this. Are these two lines interesting for other packages, too? If yes, we could add a special setting like the existing `has_HOMALG_IO` which adds `HOMALG_IO.show_banners := false;;` to `000_LoadPackage.tst`. If not, we could add a generic way for adding additional lines to `000_LoadPackage.tst`.

**Comment by mohamed-barakat** [comment]
I prefer the ability to add additional lines to `000_LoadPackage.tst`.

**Comment by zickgraf** [comment]
I just wanted to implement this, but I have a better suggestion: You can simply create a file `001_initialization.tst` and put the lines there. Then we do not have to track this in `PackageJanitor` at all -> this should be the cleanest solution :-)

**Comment by zickgraf** [comment]
Note: I plan to rename `000_LoadPackage.tst` to `100_LoadPackage.tst` to allow packages to execute commands BEFORE the packages are loaded. This can then for example be used to load a package with warnings without causing conflicts with `PackageJanitor`.

So I update my suggestion above to name the new file `200_initialization.tst`.

**Comment by mohamed-barakat** [comment]
Wonderful :)

**Comment by mohamed-barakat** [comment]
This should be now be incorporated, right?

**Comment by zickgraf** [comment]
Have you tried the suggestion in https://github.com/homalg-project/PackageJanitor/issues/47#issuecomment-737879448? If yes and if you are happy with it, we can close the issue.

**Comment by zickgraf** [comment]
@mohamed-barakat Can this be closed?

**Comment by mohamed-barakat** [comment]
Yes
