### ISSUE TITLE
permalinks structured in directories

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#58]
I would prefer to retain the concept of one directory per final link. I find this more structured.

**Comment by zickgraf** [comment]
Ah, I didn't know that GitHub actually supports transferring issues instead of closing and opening a new issue. Nice!

**Comment by zickgraf** [comment]
@mohamed-barakat I propose to close this issue with the following reasoning:

If you want a structured view of all links, you should look at the `site.yml`: https://github.com/homalg-project/PackageJanitor/blob/86451d5fe3bb90e86b5d1c046aa69c18d16b4ae4/site.yml#L995-L1021

The structure generated by `PackageJanitor` is an implementation detail and is not meant for viewing/editing.
