### ISSUE TITLE
Always set GAP dependency to the tested/stable version

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/PackageJanitor#74]
I suggest to always set the GAP dependency to the version we test in our CI, i.e. the latest stable version. Of course this is overly strict, but it would  prevent issues like https://github.com/homalg-project/homalg_project/issues/461, and properly keeping track of the lowest compatible GAP version for each package would be very time-consuming for little gain.

@mohamed-barakat Dou you agree, or should we keep the current system on bumping the dependency "on demand"?

**Comment by mohamed-barakat** [comment]
I agree, bump it automatically to what we test and can "guarantee".

**Comment by mohamed-barakat** [comment]
Probably we cannot afford testing against 4.x and 4.(x-1), right?

**Comment by zickgraf** [comment]
> Probably we cannot afford testing against 4.x and 4.(x-1), right?

If all packages would support 4.(x-1), testing that would be simple (we could simply add a third docker container). But that would be a restriction which I definitely would not like to have (waiting eagerly for 4.12 :D ), and without this restriction keeping track of which packages (including all dependency) should actually be tested with 4.(x-1) would be non-trivial.
