### ISSUE TITLE
Is there a way to add new entities?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/PackageJanitor#9]
https://github.com/homalg-project/Algebroids/blob/master/makedoc.g#L28

**Comment by zickgraf** [comment]
Currently, there is no way to add new entities. Maybe we could simply add `QPA` to the default list? I think having unused entities does not hurt and when grepping for "entities" it seems like the union of the entities of all of our packages is a rather small set.

**Comment by mohamed-barakat** [comment]
Yes, then please add `QPA`.
